type Todo {
	id: ID!
	task: String!
	complete: Boolean!
}

enum TodoEnum {
	CREATED
	UPDATED
	REMOVED
}

input TodoInput {
	id: ID
	task: String
	complete: Boolean
}

input UpdateTodo {
	task: String
	complete: Boolean
}

type TodoResponse {
	mutation: TodoEnum
	node: Todo
}

type Query {
	todos: [Todo]
}

type Mutation {
	newTodo(data: TodoInput): TodoResponse!
	editTodo(fields: UpdateTodo, where: TodoInput): TodoResponse!
	removeTodo(where: TodoInput): Boolean!
}

type Subscription {
	todo(mutation: TodoEnum): TodoResponse
}
